# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-01 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, default=None, max_length=40, null=True)),
            ],
        ),
    ]
