# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('SOL', 'Solutions'), ('APP', 'Applications'), ('INT', 'Integration'), ('DAT', 'Data'), ('INF', 'Infrastructure')], default='SOL', help_text='Dominio de arquitectura impactado por la decision', max_length=3)),
                ('notice_date', models.DateField(auto_now=True, help_text='Fecha en la que la decision es tomada')),
                ('effective_date', models.DateField(auto_now=True, help_text='Fecha en la que la decision se hace efectiva')),
                ('decision_details', models.CharField(help_text='Detalle de la decision que se toma', max_length=1000)),
                ('basis', models.CharField(blank=True, help_text='Fundamentos de la decision', max_length=500, null=True)),
                ('scope', models.CharField(blank=True, help_text='Alcance de la decision, a nivel organizacional o entorno de ejecucion', max_length=500, null=True)),
                ('impact', models.CharField(blank=True, help_text='Impacto que tiene la decision. Pueden ser componentes, areas organizacionales o proyectos, por ejemplo', max_length=500, null=True)),
                ('alternatives', models.CharField(blank=True, help_text='Alternativas que fueron evaluadas para tomar la decision', max_length=500, null=True)),
                ('affected_project', models.ForeignKey(help_text='Proyecto afectado por la decision', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('decisor', models.ForeignKey(help_text='Arquitecto que toma la decision sobre un proyecto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_decision', models.ForeignKey(help_text='Relacion con otra decision que influyo en la actual', on_delete=django.db.models.deletion.CASCADE, to='decisions.Decision')),
            ],
        ),
    ]
