# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_auto_20170108_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField(auto_now=True, help_text='Fecha que se realiza el comentario')),
                ('commenter', models.CharField(help_text='Persona que realizo el comentario (o anonimo)', max_length=20)),
                ('comment', models.CharField(help_text='Comentario sobre la decision', max_length=200)),
                ('affected_decision', models.ForeignKey(help_text='Decision afectada por el comentario', on_delete=django.db.models.deletion.CASCADE, to='decisions.Decision')),
            ],
        ),
    ]
