# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-01 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='related_decision',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Comentario que responde a otro', null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='decision_state',
            field=models.CharField(choices=[('Tomada', 'Tomada'), ('Pendiente', 'Pendiente')], default='Tomada', help_text='Estado de la decision', max_length=15),
        ),
        migrations.AddField(
            model_name='decision',
            name='related_decision_id',
            field=models.CharField(blank=True, help_text='Relacion con otras decisiones que influyeron en la actual', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(help_text='Comentario sobre la decision o sobre otro comentario', max_length=200),
        ),
        migrations.AlterField(
            model_name='decision',
            name='domain',
            field=models.CharField(choices=[('SOL', 'Soluciones'), ('APP', 'Aplicaciones'), ('INT', 'Integraciones'), ('DAT', 'Datos'), ('INF', 'Infraestructura')], default='SOL', help_text='Dominio de arquitectura impactado por la decision', max_length=3),
        ),
        migrations.AlterField(
            model_name='decision',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Fecha en la que la decision se hace efectiva', null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='notice_date',
            field=models.DateField(help_text='Fecha en la que la decision es tomada'),
        ),
    ]
